#! /bin/bash

### BEGIN INIT INFO
# Provides:             jtec_can
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:    Configure jtec_can 
### END INIT INFO

# emPC-CX+ vendor id, device id
PCI=13c3:2600

do_start() {

  modprobe jhal
  
  IRQ=$(lspci -d $PCI -v | grep IRQ | tr ' ' '\n' | tail -n1)
  ADDRESSCAN0=0x$(lspci -d $PCI -v | grep =8K | head -n 1 | grep -o '[0-9a-f]\{8\}')
  ADDRESSCAN1=$(printf "0x%X\n" $(($ADDRESSCAN0 + 0x200)))
   
  modprobe can
  modprobe can-dev
  modprobe sja1000
  #modprobe sja1000_platform
  # always two CANs, even if only one port is externally available
  modprobe jtec_can "io=0,$ADDRESSCAN0,$IRQ,$ADDRESSCAN1,$IRQ"

}

case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        rmmod jtec_can
        ;;
  *)
        echo "Usage: jtec_can [start|stop]" >&2
        exit 3
        ;;
esac


